### ISSUE TITLE
Mount point missing?

### ISSUE THREAD

**Issue by c0desurfer** [hthighway/scripts#1]
Shouldn't it be
ExecStart=/usr/bin/plexdrive mount -c /home/user/.plexdrive --cache-file=/home/user/.plexdrive/cache.bolt -v 3 -o allow_other --max-chunks=250 --refresh-interval=1m /plexmedia/plexdrive 

instead of 

ExecStart=/usr/bin/plexdrive mount -c /home/user/.plexdrive --cache-file=/home/user/.plexdrive/cache.bolt -v 3 -o allow_other --max-chunks=250 --refresh-interval=1m$

?

Because I get panic messages about missing mount points with it.

**Comment by hthighway** [comment]
Yes, it was missing the mount folder
